HelpCenterService:
    Db:
        LogsConnString:
            settings-key: HelpCenter-LogsConnString
            types:
                - AzureBlobStorage
                - Tag
        AzureRepositoriesConnString:
            settings-key: HelpCenter-AzureRepositoriesConnString
            types:
                - AzureTableStorage
    
    ZenDesk: 
        Url:
            settings-key: HelpCenter-ZenDeskUrl
        OAuthToken:
            settings-key: HelpCenter-OAuthToken

ClientAccountServiceClient:
    ServiceUrl:
        settings-key: ClientAccountServiceUrl       
          
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl       

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName: 
            settings-key: SlackQueueName