HelpCenterService:
    Db:
        LogsConnString:
            settings-key: HelpCenterService-LogsConnString
            types:
                - AzureBlobStorage
                - Tag
    
    Cache:
        RedisConfiguration:
            settings-key: HelpCenterService-RedisConfiguration
            types:
                - Redis

        ClientsCacheInstance:
            settings-key: HelpCenterService-ClientsCache
        ClientsCacheKeyPattern:
            settings-key: HelpCenterService-ClientsCacheKeyPattern

    ZenDesk: 
        Url:
            settings-key: HelpCenterService-ZenDeskUrl
        OAuthToken:
            settings-key: HelpCenterService-OAuthToken

ClientAccountServiceClient:
    ServiceUrl:
        settings-key: ClientAccountServiceUrl       
          
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl       

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName: 
            settings-key: SlackQueueName